#spring-boot允许直接使用ymal配置来注入实体类

server:
  port: 8088

netty:
  port: 12345

logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jingweimeeting?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 334331096Sql
    type: com.alibaba.druid.pool.DruidDataSource
  #application:
   # name: sunny-cloud-security

mybatis:
  mapper-locations: classpath:com/jignwei/dao/*.xml

